language: node_js
node_js: 
- 5.10.0
script: 
- grunt test
before_deploy: 
- zip -r latest *
- mkdir -p deploy
- mv latest.zip deploy/latest.zip
deploy: 
  provider: s3
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  bucket: travis-prototype
  endpoint: travis-prototype.s3-website-us-west-1.amazonaws.com
  skip_cleanup: true

