language: node_js
node_js:
  - "5.10.0"

before_script:
  - chmod +x ./run_build.sh

script:
  - ./run_build.sh

before_deploy:
  - mkdir -p build_for_deploy

deploy:
  - provider: s3
    access_key_id: access_key_id
    secret_access_key: &1
      secure: secret_access_key
    local_dir: build_for_deploy
    skip_cleanup: true
    on: &2
      repo: naumanm/Travis-Test
    bucket: travis-prototype
