language: node_js
node_js:
  - "5.10.0"

before_script:
  - chmod +x ./run_build.sh

script:
  - ./run_build.sh

deploy:
  - provider: s3
    access_key_id: access_key_id
    secret_access_key:
      secure: secret_access_key
    local_dir: release
    skip_cleanup: true
    on: &2
      repo: naumanm/Travis-Test
    bucket: travis-prototype
