language: node_js
node_js:
  - "5.10.0"

before_script:
  - npm install -g grunt-cli
  - npm install -g load-grunt-tasks
  - npm install
  - chmod +x ./run_build.sh

script:
  - which grunt
  - ls
  - grunt test
  - ./run_build.sh

deploy:
  - provider: s3
  - access_key_id: AKIAIABEZL7YS3EAQN6A
  - secret_access_key: &1
      secure: secret_access_key
  - local_dir: build_for_deploy
  - skip_cleanup: true
  - on: &2
      repo: naumanm/Travis-Test
  - bucket: travis-prototype
