language: node_js
node_js:
  - "5.10.0"

before_script:
  - chmod +x ./run_build.sh

script: ./run_build.sh

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload

deploy:
  - provider: s3
    access_key_id: access_key_id
    secret_access_key: secret_access_key
      secure:
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: naumanm/Travis-Test
    bucket: travis-prototype
