language: node_js
node_js:
  - "5.10.0"

before_script:
  - chmod +x ./run_build.sh
  - mkdir -p build_for_deploy
  - cd build_for_deploy
  - npm install grunt-cli -g

script: ../run_build.sh

deploy:
  - provider: s3
  - access_key_id: AKIAIABEZL7YS3EAQN6A
  - secret_access_key: &1
      secure: secret_access_key
  - local_dir: build_for_deploy
  - skip_cleanup: true
  - on: &2
      repo: naumanm/Travis-Test
  - bucket: travis-prototype
