language: node_js
node_js: 
  5.10.0
script:
- grunt test
- grunt build
- grunt deploy-release
deploy:
  provider: s3
  access_key_id: $aws_access_key_id
  secret_access_key: $aws_secret_access_key
  aws_region: $aws_region
  bucket: $aws_bucket


