language: node_js
node_js:
  "5.10.0"

before_script:
  chmod +x ./run_build.sh

script:
  ./run_build.sh

before_deploy:
  mkdir -p build_for_deploy

deploy:
  provider: s3
  access_key_id: access_key_id
  secret_access_key: secret_access_key
  bucket: travis-prototype
  skip_cleanup: true