language: node_js
node_js:
  - "5.10.0"

script: ./run_build.sh

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload

deploy:
  - provider: s3
    access_key_id:
    secret_access_key: &1
      secure:
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: naumanm/Travis-Test
    bucket: travis-prototype
